logging:
    config: classpath:logback.xml
xxl:
    job:
        accessToken: ''
        admin:
            addresses: http://192.168.130.202:8093/xxl-job-admin
        executor:
            address: ''
            appname: stockExecutor
            ip: ''
            logpath: /data/applogs/xxl-job/jobhandler
            logretentiondays: 30
            port: 9999
